# Generated by Django 3.0.7 on 2020-11-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphonenumber', models.CharField(blank=True, help_text='Your phone number', max_length=20, null=True, unique=True)),
                ('medical_practitioner', models.BooleanField()),
                ('job_title', models.CharField(blank=True, help_text='Your job description', max_length=100, null=True)),
                ('user', models.OneToOneField(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
